### ISSUE TITLE
运行train.py出现问题

### ISSUE THREAD

**Issue by xiangyonghong123** [bubbliiiing/efficientdet-pytorch#36]
runfile('E:/A/efficientdet-pytorch-master/train.py', wdir='E:/A/efficientdet-pytorch-master')
Reloaded modules: nets, nets.efficientdet, utils, utils.anchors, nets.efficientnet, nets.layers, nets.efficientdet_training
Traceback (most recent call last):

  File "D:\software\Anaconda\envs\torch1.2\lib\site-packages\torch\utils\tensorboard\__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401

ModuleNotFoundError: No module named 'tensorboard.summary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\A\efficientdet-pytorch-master\train.py", line 16, in <module>
    from utils.callbacks import LossHistory

  File "E:\A\efficientdet-pytorch-master\utils\callbacks.py", line 9, in <module>
    from torch.utils.tensorboard import SummaryWriter

  File "D:\software\Anaconda\envs\torch1.2\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '

ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.
![image](https://user-images.githubusercontent.com/76210255/163706543-5dd000e8-9b1f-47ac-a856-82502e5cd8f0.png)

**Comment by xiangyonghong123** [comment]
并且在下载efficientdet-d0.pth后，运行predict.py出现以下问题：
![image](https://user-images.githubusercontent.com/76210255/163706581-5b7aed69-fe50-4031-b26e-6e97cb31a8f0.png)

**Comment by xiangyonghong123** [comment]
我重新安装环境并使用vscode后可以进行train.py的运行，训练一轮后出现该错误：
![image](https://user-images.githubusercontent.com/76210255/163767261-e201b0b6-9a98-4fdf-b4f7-957879b75cd7.png)
我将对应环境的libiomp5md.dll删除后，可以进行接下来的训练，但是每一次的训练都会出现停止再训练，请问该怎么去更正呢？
![image](https://user-images.githubusercontent.com/76210255/163767220-fc5350e3-6cb6-4834-bca1-db11ae19a4d0.png)
![image](https://user-images.githubusercontent.com/76210255/163767557-2950e59f-4cab-4779-b6c9-327381d92257.png)

**Comment by bubbliiiing** [comment]
你的环境是什么？

**Comment by xiangyonghong123** [comment]
> 你的环境是什么？
![image](https://user-images.githubusercontent.com/76210255/163828551-f04fff6d-b1e0-4ae8-9cba-75c102aca583.png)
按照您的博客进行的配置

**Comment by xiangyonghong123** [comment]
> 你的环境是什么？

《深度学习环境配置2——windows下的torch=1.2.0环境配置》

**Comment by bubbliiiing** [comment]
cuda和cudnn，根据问题汇总自查一下是什么

**Comment by jspenliany** [comment]
https://zhuanlan.zhihu.com/p/371649016...参考这个修改。原因是这个dll重复了
