### ISSUE TITLE
predict遇到问题

### ISSUE THREAD

**Issue by yangkang121** [bubbliiiing/efficientdet-pytorch#54]
Traceback (most recent call last):
  File "E:\yk\Code\efficientdet-pytorch\predict.py", line 77, in <module>
    r_image = efficientdet.detect_image(image, crop = crop, count=count)
  File "E:\yk\Code\efficientdet-pytorch\efficientdet.py", line 216, in detect_image
    draw.rectangle([left + i, top + i, right - i, bottom - i], outline=self.colors[c])
  File "D:\Anaconda\envs\objectbox\lib\site-packages\PIL\ImageDraw.py", line 296, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
ValueError: x1 must be greater than or equal to x0

作者大大好，我在使用d3预训练权重进行预测时，出现了这个错误，不知道是什么原因

**Comment by yangkang121** [comment]
已解决
