### ISSUE TITLE
配置完环境运行predict失败

### ISSUE THREAD

**Issue by LittleKing6** [bubbliiiing/efficientdet-pytorch#58]
Traceback (most recent call last):
  File "predict.py", line 14, in <module>
    efficientdet = Efficientdet()
  File "/home/wwl/code/efficientdet-pytorch-master/efficientdet.py", line 87, in __init__
    self.generate()
  File "/home/wwl/code/efficientdet-pytorch-master/efficientdet.py", line 101, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "/home/wwl/anaconda3/envs/EffcientNet/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/wwl/anaconda3/envs/EffcientNet/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/wwl/anaconda3/envs/EffcientNet/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model_data/efficientdet-d0.pth'
一直是跟着b站博主视频来的，下的也是这个包 问题会出在哪呢T T

**Comment by jspenliany** [comment]
你这个最后一行提升了，没有模型文件efficientdet-d0.pth啊。你需要下载了这个文件放在model_data目录下
