### ISSUE TITLE
训练预测出现问题

### ISSUE THREAD

**Issue by Clarences1995** [bubbliiiing/efficientdet-pytorch#6]
你好，我训练完50个epoch之后重新加载测试模型，出现了以下错误信息，是我没有改fc的输出导致的吗？谢谢
Traceback (most recent call last):
  File "/home/yueyu/efficientdet-pytorch/predict.py", line 7, in <module>
    efficientdet = EfficientDet()
  File "/home/yueyu/efficientdet-pytorch/efficientdet.py", line 53, in __init__
    self.generate()
  File "/home/yueyu/efficientdet-pytorch/efficientdet.py", line 74, in generate
    self.net.load_state_dict(state_dict)
  File "/home/yueyu/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDetBackbone:
        size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([180, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([36, 64, 1, 1]).
        size mismatch for classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([180]) from checkpoint, the shape in current model is torch.Size([36]).

**Comment by bubbliiiing** [comment]
问题汇总

**Comment by qingHX** [comment]
I have the same problem.Thanks!!!!!!

**Comment by qingHX** [comment]
That's My fault. The file name is wrong. Thanks!!!
